### ISSUE TITLE
Review README

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/masquerade#26]
It seems that run options on the current Firefox do not require marionette setting any more

**Comment by mariodavid** [comment]
Hi @jreznot,

first of all: this is a really great project. This is really cool. I've tried it in this repo here: https://github.com/mariodavid/rtcab-ordermanagement-test.

I was able to run it in IDEA without any additional VM options. In fact, I do not even need the `geckodriver` in order to run the tests.

Environment:
Mac OS X 10.13.3
Firefox 59.0.0.2 (64 Bit)

So, perhaps it is really not necessary to set this settings anymore. In fact, when I configure the `-Dselenide.browser=marionette` setting, there is an error while running the tests.

Bye
Mario

**Comment by jreznot** [comment]
Rework tutorial and replace Firefox options with Chrome
